//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsDatabase
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public string Things_to_do { get; set; }
        public string Note { get; set; }
        public string Priority_Level { get; set; }
    
        public virtual Lv Lv { get; set; }
    }
}
